name: Manually Triggered Docker Build

on:
  workflow_dispatch:

jobs:
  build-and-save:
    runs-on: ubuntu-24.04-arm

    steps:
    - name: Check out the code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # - name: Cache Docker layers
    #   uses: actions/cache@v4
    #   with:
    #     path: /tmp/.buildx-cache
    #     key: ${{ runner.os }}-buildx-${{ github.sha }}
    #     restore-keys: |
    #       ${{ runner.os }}-buildx-

    - name: Build Docker image
      run: |
        docker build --tag nginx:1.27.5_mod -f Dockerfile .

    - name: Save Docker image
      run: |
        docker save nginx:1.27.5_mod -o nginx.tar

    - name: Compress Docker image
      run: |
        gzip nginx.tar

    - name: Upload Docker image as an artifact
      uses: actions/upload-artifact@v4
      with:
        name: docker-image
        path: nginx.tar.gz
